
project_id = "kweskshyumqhijjileky"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_tokens = true
refresh_token_reuse_interval = 10
enable_signup = true

[realtime]
enabled = true

[storage]
enabled = true

[[storage.buckets]]
name = "avatars"
public = true
file_size_limit = "5MB"
allowed_mime_types = ["image/png", "image/jpeg", "image/gif"]

[analytics]
enabled = false
port = 54327
vector_port = 54328
