
project_id = "kweskshyumqhijjileky"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[functions]
[functions.send-notification]
verify_jwt = true

[functions.chat-server]
verify_jwt = true

[functions.migration-status]
verify_jwt = true

[functions.health-check]
verify_jwt = true

[functions.trigger-backup]
verify_jwt = true
