// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kweskshyumqhijjileky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZXNrc2h5dW1xaGlqamlsZWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDgyNTYsImV4cCI6MjA2MTUyNDI1Nn0.Qo-OpAXUOP-W_XYbAzlo61wtzjMlpja0imTNR-eLKJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);